### PR TITLE
bower > npm

### PR DESCRIPTION
**Pull request by jgravois**
freshen up doc by removing references to bower and replacing them with links to npm and webpack.

### CODE REVIEW

**Comment by rsjones** [comment]
Considering that the webpack work only works with 4.x I would suggest also keeping references to the other build types.

**Comment by jgravois** [comment]
this is a PR against `4master`

**Comment by rsjones** [comment]
I'm assuming one day `4master` will become `master` and we have many clients that can't necessarily move that fast. I'd hate for them to spin on information that doesn't apply to their version.

**Comment by jgravois** [comment]
> I'm assuming one day `4master` will become `master`

given the trajectory of JS tooling, another round of copy editing will most certainly be necessary by then.

**Comment by ez4gis** [comment]
just fyi, it appears there is a typo. the url [Webpack](https://webpackjs.org) doesn't load in browser.  probably meant to reference "https://webpack.js.org/"...

**Pull request merged**
